CREATE DATABASE CURD;
USE CURD;

CREATE TABLE PEOPLE(
PERSON_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
NAME VARCHAR(32),
AGE INT,
COUNTRY VARCHAR(32),
JOINED DATE NOT NULL,
PRIMARY KEY (PERSON_ID) 
);
INSERT INTO PEOPLE VALUES(DEFAULT,'JACK',34,'INDIA','2021-9-12');
INSERT INTO PEOPLE VALUES(DEFAULT,'MARIE',21,'FRANCE','2022-12-9');
INSERT INTO PEOPLE VALUES(DEFAULT,'LAURA',21,DEFAULT,'2022-12-9');
INSERT INTO PEOPLE VALUES(DEFAULT,'PREETI',32,'FRANCE','2022-12-9');

SELECT * FROM PEOPLE;
SELECT NAME,COUNTRY FROM PEOPLE;
SELECT * FROM PEOPLE WHERE NAME='DEFAULT';
SELECT * FROM PEOPLE WHERE AGE >=30;
SELECT * FROM PEOPLE WHERE AGE>=30 AND COUNTRY='INDIA';

-- ORDER BY KA SIMPLE SA MTB HOTA HAI KISI BI CHIZ KO USKE SPECIFIC ORDER MAI LAGANA USSE UPR NICHE BI PEOPLE ID HO SKTI HAI USSE KOI DIKKAT NAHI HAI 
SELECT * FROM PEOPLE ORDER BY AGE DESC;

-- TOP THREE OLDEST PERSON
SELECT * FROM PEOPLE ORDER BY AGE DESC LIMIT 3;






-- UPDATE SPECIFIC RECORD
-- SET @SAFE_UPDATE_MODE=TRUE;
UPDATE PEOPLE SET AGE=35 WHERE NAME='JACK';
UPDATE PEOPLE SET AGE=56,COUNTRY='GERMANY' WHERE NAME='LAURA';
SELECT * FROM PEOPLE ;



--  IMPORTANT TIPS
START TRANSACTION;
UPDATE PEOPLE SET AGE=35;
SELECT * FROM PEOPLE;
ROLLBACK;
SELECT * FROM PEOPLE;
COMMIT;



-- DELETE
DELETE FROM PEOPLE;
DELETE FROM PEOPLE WHERE AGE>=30;

START TRANSACTION;
DELETE FROM PEOPLE;
ROLLBACK;




